name:                penntreebank-megaparsec
version:             0.1.0
synopsis:            Parser combinators for trees in the Penn Treebank format
description: |
    This Haskell package provides parsers for syntactic trees annotated 
    in the Penn Treebank format, powered by Megaparsec.
github:              aslemen/penntreebank-megaparsec
license:             BSD3
author:              Nori Hayashi
maintainer:          Nori Hayashi <net@hayashi-lin.net>
copyright:           2020 Nori Hayashi
category:            Parsing, Natural Language Processing

#  try to keep align with that of Megaparsec
tested-with: GHC==8.4.4, GHC==8.6.5, GHC==8.8.1

extra-source-files:
- README.md

dependencies:
  - base >= 4.11 && < 5
  - containers >=0.5 && <0.7
  - mtl >= 2.2.2 && < 3
  - transformers >=0.4 && < 0.6
  - megaparsec >= 8.0 && < 9

library:
  source-dirs: src

tests:
  unit-tests:
    source-dirs:
      - test/unit
    main: Spec.hs
    dependencies:
      - penntreebank-megaparsec
      - hspec >= 2.0 && < 3.0
      - text >= 0.2 && < 1.3
    build-tools:
      - hspec-discover
    ghc-options: 
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N